//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Comments = new HashSet<Comment>();
            this.Dislikes = new HashSet<Dislike>();
            this.Images = new HashSet<Image>();
            this.Likes = new HashSet<Like>();
            this.Problems = new HashSet<Problem>();
            this.UserAttemptedProblems = new HashSet<UserAttemptedProblem>();
            this.UserSolvedProblems = new HashSet<UserSolvedProblem>();
            this.Videos = new HashSet<Video>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Dislike> Dislikes { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Problem> Problems { get; set; }
        public virtual ICollection<UserAttemptedProblem> UserAttemptedProblems { get; set; }
        public virtual ICollection<UserSolvedProblem> UserSolvedProblems { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
