//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public Problem()
        {
            this.Answers = new HashSet<Answer>();
            this.Comments = new HashSet<Comment>();
            this.Dislikes = new HashSet<Dislike>();
            this.Images = new HashSet<Image>();
            this.Likes = new HashSet<Like>();
            this.UserAttemptedProblems = new HashSet<UserAttemptedProblem>();
            this.UserSolvedProblems = new HashSet<UserSolvedProblem>();
            this.Videos = new HashSet<Video>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public int CategoryId { get; set; }
        public string Author_Id { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Dislike> Dislikes { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<UserAttemptedProblem> UserAttemptedProblems { get; set; }
        public virtual ICollection<UserSolvedProblem> UserSolvedProblems { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
